### PR TITLE
Fixes issues with firefox and safari.

### PR DESCRIPTION
**Pull request by zorkow**
These are the workarounds for the issues regarding voice events on Firefox.
@dpvc can you have a look if this works for Safari as well?

### CODE REVIEW

**Review by dpvc — CHANGES_REQUESTED** [review]
This is still not working with Firefox, but that seems to be due to the fact that the `role` attributes are missing.  I think you did something in SRE to fix this, but I don't have that updated SRE, so my Firefox isn't working.

Safari is nearly working.  I can click to activate the explorer, and use keyboard to move around the equation, and the speech and braille show up properly.  But if the explorer is active, then clicking does not select the clicked item.  I tracked this down in the code, and the difference between Safari and Chrome is in how this line

https://github.com/mathjax/MathJax-src/blob/d17d8f0d0010c78160dcebeee296c8df3c89eafe/ts/a11y/explorer/KeyExplorer.ts#L180

is handled. In Safari (and presumably Firefox for you), when the `tabindex` is removed, the browser fires a focus-out even immediately, and the KeyExplorer's `FocusOut` method is called immediately before the rest of the `Click` handler is run.  In particular, that means that the `Stop()` method will be run before the rest of the `Click` method, and so `this.active` will be set to `false` before `this.Start()` is run at line 184.

In Safari, moving the `tabindex` does **not** fire a focus-out event, so `this.active` is still `true` when `this.Start()` is called, and because `Start()` returns if `this.active` is true on this line

https://github.com/mathjax/MathJax-src/blob/d17d8f0d0010c78160dcebeee296c8df3c89eafe/ts/a11y/explorer/KeyExplorer.ts#L452

in Safari, the rest of the `Start()` doesn't run, and the selected node is never switched.

One solution would be to add

``` js
this.FocusOut(null);
```

right after line 180 shown above.  That will force the focus-out action in Safari, and for browsers that fire a focus-out event at this point, it should still be OK since `FocusOut()` exists if `this.active` is false, as it should be after the first `FocusOut()` is run.  Of course, you might have a better idea for this.

I'll have to check Firefox again once I have the SRE update that allows the `role` attributes to be inserted.

**Comment by dpvc** [comment]
Here are the list of continuing issues from our chat today:

* Hover highlighting leads to an error.
* While explorer is active, all key events are blocked (including reload, etc.)
* Can't start explorer if both speech and braille are unchecked.  I believe that this is due to the fact that there are no role attributes in that case, because those seem to be added during the speech/braille creation at
* 
* , which isn't being called

**Comment by dpvc** [comment]
Here are the list of continuing issues from our chat today:

* Hover highlighting leads to an error.
* While explorer is active, all key events are blocked (including reload, etc.)
* Can't start explorer if both speech and braille are unchecked.  I believe that this is due to the fact that there are no role attributes in that case, because those seem to be added during the speech/braille `creationSpeech()` function in semantic-enrich, which isn't being called.
* After a change in language, you must do a move to get new language (but you know this one already).

**Comment by dpvc** [comment]
I figured out the third issue above, and have fixed it in my menu update branch (not yet pushed).

**Comment by dpvc** [comment]
> That was actually an issue related to how explorers were attached.

I fixed it in the `sre-menus` branch, as I mentioned above, so you don't need to worry about that one.

**Comment by zorkow** [comment]
> After a change in language, you must do a move to get new language (but you know this one already).

This is now fixed. However, we still have an issue when changing rule sets/preference settings. I will tackle this in a new PR to simplify review.

**Comment by zorkow** [comment]
@dpvc as discussed today, this should be ready to merge.

**Review by dpvc — APPROVED** [review]
This all seems to work now, except that I still can't get hover or flame highlighting to work.  But I may not know what I'm doing, so that may be the problem.  We can chat about it in our next meeting.

**Pull request merged**
